module "eks-cluster" {
  	source = "git@github.tfs.toyota.com:dne-cloud/eks-deploy-tf-modules.git//tfsdne-aws-eks?ref=v2.1.1"
	region = var.region
        cluster_version = var.cluster_version
        map-migrated = var.map-migrated
        MPE = var.MPE
	this-account-id = var.this-account-id
	this-git-repo = var.this-git-repo
	profile = var.profile
	assume-role = var.assume-role
	key_pair = var.key_pair
	environment_identifier = var.environment_identifier
	random_string = var.random_string
	SnowEnvironment = var.SnowEnvironment
	SnowChargeCode = var.SnowChargeCode
	SnowAppName = var.SnowAppName
	vpc_id = var.vpc_id
	subnet_ids = var.subnet_ids
	node_instance_type = var.node_instance_type
	maxpods = var.maxpods
	additional_eks_sgs = var.additional_eks_sgs
	existing_node_sg = var.existing_node_sg
	auto_scaling_min_size = var.auto_scaling_min_size
	auto_scaling_max_size = var.auto_scaling_max_size
	auto_scaling_desired_size = var.auto_scaling_desired_size
	activate-blue-asg = var.activate-blue-asg
	activate-green-asg = var.activate-green-asg
}
