apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::009754696474:role/eks-dev-0122-worker-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-network-admin
      username: tfsawssubprod-network-admin
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-dev-admin-role
      username: eks-dev-admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-cloud-admin
      username: tfsawssubprod-cloud-admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-compute-admin
      username: tfsawssubprod-compute-admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-jenk-role
      username: k8s-dev-jenk
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-idec-role
      username: k8s-dev-idec
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-dsab-role
      username: k8s-dev-dsab
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-pae2kg-role
      username: k8s-dev-pae2kg
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-eas13g-role
      username: k8s-dev-eas13g
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-feoc6v-role
      username: k8s-dev-feoc6v
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-signjl-role
      username: k8s-dev-signjl
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-deeejm-role
      username: k8s-dev-deeejm
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-cimswz-role
      username: k8s-dev-cimswz
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-mftf9-role
      username: k8s-dev-mftf9
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-endhld-role
      username: k8s-dev-endhld
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-nicx3i-role
      username: k8s-dev-nicx3i
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-cronm7-role
      username: k8s-dev-cronm7
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-webcts-role
      username: k8s-dev-webcts
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-inid7i-role
      username: k8s-dev-inid7i
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-antak3-role
      username: k8s-dev-antak3
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-forgud-role
      username: k8s-dev-forgud
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-k8s-dev-jenk-role
      username: k8s-dev-jenk
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-dev-aslm21-role
      username: k8s-dev-aslm21
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-monitoring-admin
      username: tfsawssubprod-monitoring-admin
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-tf-full-admin
      username: tfsawssubprod-tf-full-admin
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-service-servicenow-role
      username: servicenow-read-only-user
      groups:
        - system:authenticated
    - userarn: arn:aws:iam::009754696474:role/tfsawssubprod-eks-k8s-monitoring-tools-role
      username: tfsawssubprod-monitoring-admin
      groups:
        - system:authenticated          
