variable "region" {}
variable "this-account-id" {}
variable "profile" {}
variable "assume-role" {}
variable "key_pair" {}
variable "environment_identifier" {}
variable "random_string" {}
variable "SnowEnvironment" {}
variable "SnowChargeCode" {}
variable "SnowAppName" {}
variable "map-migrated" {}
variable "MPE" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "node_instance_type" {}
variable "maxpods" {}
variable "additional_eks_sgs" {}
variable "existing_node_sg" {}
variable "auto_scaling_min_size" {}
variable "auto_scaling_max_size" {}
variable "auto_scaling_desired_size" {}
variable "this-git-repo" {}
variable "activate-blue-asg" {}
variable "activate-green-asg" {}
