kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-gp3
provisioner: ebs.csi.aws.com
parameters:
   type: gp3
   fsType: ext4
   encrypted: "true"
   kmsKeyId: {{EBS_KMS_KEY_ARN}}
volumeBindingMode: WaitForFirstConsumer
mountOptions:
- debug
allowVolumeExpansion: true
