## Make sure to replace the account aliase with the actual account alias

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{accountalias}}-network-admin-rolebind
  namespace: twistlock
subjects:
- kind: User
  name: {{accountalias}}-network-admin
  namespace: twistlock
roleRef:
  kind: ClusterRole
  name: tfsekstoolscluster-role
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{accountalias}}-network-admin-rolebind
  namespace: network-tools
subjects:
- kind: User
  name: {{accountalias}}-network-admin
  namespace: network-tools
roleRef:
  kind: ClusterRole
  name: tfsekstoolscluster-role
  apiGroup: rbac.authorization.k8s.io
