apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: servicenow-read-only-clusterrolebind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: servicenow-read-only-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: servicenow-read-only-user