kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tfsessubprod-monitoring-admin-rolebind
  namespace: monitoring-tools
subjects:
- kind: User
  name: tfsessubprod-monitoring-admin
  namespace: monitoring-tools
roleRef:
  kind: ClusterRole
  name: tfsekstoolscluster-role
  apiGroup: rbac.authorization.k8s.io
