kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tfsekstoolscluster-role
rules:
- apiGroups: ["events.k8s.io", ""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","list", "create", "patch", "delete", "update"]
- apiGroups: [""]
  resources:
  - configmaps
  - endpoints
  - limitranges
  - persistentvolumeclaims
  - pods
  - pods/log
  - pods/exec
  - pods/portforward
  - pods/attach
  - pods/proxy
  - podtemplates
  - replicationcontrollers
  - serviceaccounts
  - services
  verbs: ["*"]
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["list", "get", "watch"]
- apiGroups: ["batch", "apps", "extensions", "autoscaling", "coordination.k8s.io", "policy", "rbac.authorization.k8s.io"]
  resources:
  - cronjobs
  - deployments
  - horizontalpodautoscalers
  - ingresses
  - daemonsets
  - jobs
  - leases
  - poddisruptionbudgets
  - replicasets
  - rolebindings
  - roles
  - statefulsets
  verbs: ["*"]
